#!/bin/sh

BRANCH_NAME=$(git symbolic-ref --short HEAD)
NUMBER=$(git branch | grep \* | sed 's/[^0-9]*//g')
BRANCH_STARTSWITH=(feature)
PREPEND=0

for PREFIX in "${BRANCH_STARTSWITH[@]}"
do
    if [[ $BRANCH_NAME == $PREFIX* ]]; then
        PREPEND=1
        break
    fi
done

if [ "$PREPEND" -eq 1 ] && [ -n "$NUMBER" ]; then
  sed -i -e "1s/^$/. refs #$NUMBER/" $1
fi
